### ISSUE TITLE
Multisig create from pubkeys fails

### ISSUE THREAD

**Issue by agouin** [vitwit/resolute#1160]
![image](https://github.com/vitwit/resolute/assets/6722152/f4bbe1f4-7418-4c06-ba22-fc664b49ef2a)

I am attempting to create a multisig without the individual signer accounts existing on-chain (with pubkeys instead of addresses). This operation fails with the toast alert saying, "failed to create multisig account". Upon inspection in the developer tools, the error response from the API is:

```json
{
  "status": "error",
  "message": "failed to create multisig account",
  "log": "pq: value too long for type character varying(20)"
}
```

It appears that there is a bug when dealing with the length of the base64 pubkeys.

**Comment by aleem1314** [comment]
Hey @agouin 

Thanks for reporting the issue. It happened because backend only allowed multisig name is up to 20 characters long. We've changed it so now you can use multisig name up to 100 characters. You should be able to create the multisig without any issues now. We'll make sure to improve our error messages for situations like this in the future.

cc: @charymalloju @Hemanthghs

**Comment by agouin** [comment]
Thank you @aleem1314 ! I can confirm we are now able to create the multisig using the public keys.
